owner: jozefcipa
repo: status.zvonydudas.sk

sites:
  - name: ZvonyDudas API
    url: https://api-v2.zvonydudas.sk/

status-website:
  cname: status.zvonydudas.sk
  theme: light
  logoUrl: https://zvonydudas.sk/img/logo.jpg
  navbar:
    - title: zvonydudas.sk
      href: https://zvonydudas.sk
  robotsText: "User-agent: * \n Disallow: /"

assignees:
  - jozefcipa
